### ISSUE TITLE
accept-regex fails to capture anything

### ISSUE THREAD

**Issue by jimpriest** [ArchiveTeam/wpull#321]
I've been experimenting with wpull all day and making good progress but have an issue with regex...

What I'm trying to solve. We have a large Drupal site which I'm trying to make a static copy of for failover.  My issue - we have several sections of our site which have dynamic 'filters' which result in URLs like:

```
mydomain.com/en/resources?f[0]=field_resource_product%3A781
mydomain.com/en/resources?f[0]=field_resource_product%3A781&f[1]=field_resource_type%3A921&rset1_format=list
```

The good: my initial tests with wpull to filter these out have been successful using:

`wpull mydomain.com --reject-regex "/resources[?]"`

But what I'd also like to do (in another wpull run) is only accept those URLs but so far haven't had any success.

I thought it would be as simple as changing things to use accept-regex:

`wpull mydomain.com --accept-regex "/resources[?]"`

But I've tried a lot of different versions of this:  "resources.*" etc etc but wpull doesn't fetch any files.

Any help would be appreciated!
Jim

**Comment by chfoo** [comment]
When `wpull mydomain.com --accept-regex "/resources[?]"` is provided, the starting URL is `http://mydomain.com`. The regex `/resources[?]` is tested against it and since it doesn't match, it won't download it. If the homepage contains all the links, you'll need to make the regex accept both the homepage URL only and the resource URLs. If you need help, there's websites that help test and visualize matching such as http://pythex.org/.

**Comment by jimpriest** [comment]
So I have

> mydomain.com/en
> mydomain.com/en/resources?f[0]foo
> mydomain.com/en/resources?f[0]bar
> mydomain.com/en/resources/
> mydomain.com/en/resources/foo.html
> mydomain.com/en/resources/bar.html

All I want are:

> mydomain.com/en/resources?f[0]foo
> mydomain.com/en/resources?f[0]bar

And I came up with something like:

`.*/en/resources[?].*|.*/en/`

Which shows correctly in pythex as matching the root AND my page but not /resources/

But doesn't fetch any pages?

I'm not the best at regex but this appears to be correct?

I also tried --exclude-directories - but that did appear to fetch pages, then remove them after they were downloaded.

Thanks!
Jim

**Comment by ivan** [comment]
`/resources[?]` can't match `/resources/` because `[?]` is just a literal question mark and is not optional

**Comment by ivan** [comment]
Oh, never mind, I really have no idea why that wouldn't fetch *any* pages

**Comment by jimpriest** [comment]
I think I have it... 

> mydomain.com/en/resources  << this is the source of my links below
> mydomain.com/en/resources?f[0]foo
> mydomain.com/en/resources?f[0]bar
> mydomain.com/en/resources/foo/
> mydomain.com/en/resources/foo/bar/

And my rule is:
`--accept-regex '.*/en/resources[?].*|.*/en/resources'  --exclude-directories /resources/`

This still seems to pull down content in  /resources/ but cleans it up afterward.  I tried using both --accept-regex and --reject-regex but couldn't get that to work.
