### ISSUE TITLE
--warc-max-size doesn't work for me

### ISSUE THREAD

**Issue by Svekla** [ArchiveTeam/wpull#334]
Hi! When I want to crawl any site with warc-max-size set it doesn't split WARC files, for example:
`wpull "iv.pl" -U 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36' -o iv.pl.log --database iv.pl.db --html-parser html5lib --save-cookies ciastko --no-check-certificate --no-robots --delete-after --page-requisites --no-parent --sitemaps --inet4-only  --timeout 25 --tries 3 --waitretry 7 --warc-file iv.pl-18082016 --warc-cdx --warc-max-size 1048576 --warc-move donewarc --strip-session-id --escaped-fragment --session-timeout 63200 --max-redirect 10 --recursive --level inf --span-hosts-allow page-requisites,linked-pages --concurrent 4 --random-wait --monitor-disk 500m`
(Test crawl, so warc-max-size is set at low value - 1MB, on other values it doesn't work as well)

And after a few moments WARC file gets around 100MB without splliting:
https://i.imgur.com/9rvIDut.png

Log after passing ~2MB: [iv.pl.txt](https://github.com/chfoo/wpull/files/425387/iv.pl.txt)

OS: Ubuntu 16.04
Python: Python 3.5.2
Wpull: 2.0.1

Thanks for help.

**Comment by falconkirtaran** [comment]
I noticed that WebSession calls _current_session.recycle() in its __exit__, but does not fire self._current_session.SessionEvent.end_session, with the result that it never actually checks the warc size (unless you are grabbing FTP).  I'll PR my fix as soon as I've tested it.

**Comment by JustAnotherArchivist** [comment]
Fixed by a4c6e92d in #348.
