### ISSUE TITLE
[1.2.3] AssertionError: Expect conn created. Got dead.

### ISSUE THREAD

**Issue by JRWR** [ArchiveTeam/wpull#379]
Running under the NewsGrabber-Warrior Pipline on AARM64 (wpull installed with pip3 install --user wpull==1.2.3) I'm getting a crash with the following

https://gist.github.com/anonymous/59834f1cffdef11eb0be81ca572299f4

Gist of Output with debug and concurrent set to 1

**Comment by chfoo** [comment]
Is #318 related?

**Comment by JRWR** [comment]
Yep, I'm running 3.5.1-3

On a side note, wpull latest does work fine on that version.
