### ISSUE TITLE
Connections to Localhost

### ISSUE THREAD

**Issue by 0xbzho** [ArchiveTeam/wpull#389]
Using wpull on a Wordpress-based blog I see logs such as:

    Could not connect to ws://127.0.0.1:29000, retrying in 8.0 seconds...

Crawling localhost by default surprised me. If the archive generated is then distributed or made available to another user on the crawling system, there is a potential for unintentional information disclosure. If this behaviour is to be default I suggest examining whether file:// URLs are permitted and how same-origin policies are validated. My preference would be that crawling localhost is opt-in.

**Comment by JustAnotherArchivist** [comment]
I don't know what this log message is, but it's not generated by wpull. I don't think wpull has *any* support for WebSockets, by the way.

But as far as I know, you're right that wpull would retrieve content from the local machine if there's a corresponding link, redirect, or DNS response. This isn't wpull-specific though. I'm pretty sure that both wget (remember that wpull tries to be wget-compatible) and all browsers would do the same by default. It's worth noting though that there are browser addons which will block such requests; NoScript does that by default, for example.

There are several options for preventing sensitive data from entering into a crawl:
* The obvious and safest one: don't run the crawl on a system with sensitive data.
* Configure the system such that the crawl can't connect to 127.0.0.0/8. For example, you could run the crawl under a dedicated user and set up an iptables rule to drop any connections by that user to 127.0.0.0/8 on the relevant ports (21, 80, and 443).
* Use a wpull hook to skip any such connections. The `handle_pre_response` hook would probably be the best choice; check where the request would be sent and return `wpull.application.hook.Actions.FINISH` for the requests you want to block. You could also hook into the DNS resolution (`resolve_dns` hook) and raise a `DNSError` if a domain resolves to 127.0.0.0/8, but this would not work for links directly pointing to an IP in 127.0.0.0/8.

**Comment by ethus3h** [comment]
This message is from the [grab-site](https://github.com/ludios/grab-site) tool, which uses wpull internally. It just means that the `gs-server` process that shows the crawls dashboard isn't running. I think it can be safely ignored.
