### ISSUE TITLE
Travis-CI badge in README is for a different repository

### ISSUE THREAD

**Issue by machawk1** [ArchiveTeam/wpull#438]
*What I wanted:* (Describe briefly what you want to achieve here)
 Travis-CI badge to be representative.

*What I expect:* (Describe briefly how you think the program/feature will work)
A URI for the badge for this repo.

*What happened:* (Describe briefly what actually happened instead)
URI of badge is for a different repo (chfoo's)

**Comment by JustAnotherArchivist** [comment]
Nice catch. Apparently Travis CI does not like/handle repository renames. This is in fact the same repository (as you can see by https://github.com/chfoo/wpull redirecting here); it was moved to the ArchiveTeam organisation a while ago.
