### ISSUE TITLE
"INFO Fetching" shown *after* file is downloaded

### ISSUE THREAD

**Issue by ivan** [ArchiveTeam/wpull#57]
Downloading a directory of big files from localhost, I see wpull printing all of the statuses for the request only _after_ it's done; each of these downloads print their corresponding log lines near-simultaneously:

```
INFO Fetching ‘http://localhost:8888/bigfiles/urandom’.
Requesting http://localhost:8888/bigfiles/urandom... 200 OK
Length: 188219392 [text/html]
100.0% [=========================] 179.5 MiB 0:00:00 290.0 MiB/s
Bytes received: 188219392
INFO Fetched ‘http://localhost:8888/bigfiles/urandom’: 200 OK. Length: 188219392 [text/html].
```

```
INFO Fetching ‘http://localhost:8888/bigfiles/connection-setup-times.txt’.
Requesting http://localhost:8888/bigfiles/connection-setup-times.txt... 200 OK
Length: 793562589 [text/plain]
97.1% [======================== ] 735.0 MiB 0:00:02 330.2 MiB/s
Bytes received: 793562589
INFO Fetched ‘http://localhost:8888/bigfiles/connection-setup-times.txt’: 200 OK. Length: 793562589 [text/plain].
```

```
INFO Fetching ‘http://localhost:8888/bigfiles/______bigfile’.
Requesting http://localhost:8888/bigfiles/______bigfile... 200 OK
Length: 232075264 [text/html]
83.6% [=====================    ] 185.0 MiB 0:00:00 267.0 MiB/s
Bytes received: 232075264
INFO Fetched ‘http://localhost:8888/bigfiles/______bigfile’: 200 OK. Length: 232075264 [text/html].
```

To be more specific, I see the download complete or nearly-complete (with no messages being printed), then I see the progress bar go from 0% to 100% at 330MB/s instead of the actual 50MB/s download speed, then the `INFO Fetched` conclusion.

**Comment by JustAnotherArchivist** [comment]
This is no longer an issue, right? I've definitely never seen it happen on recent versions of wpull (1.2.3 or 2.x).

**Comment by ivan** [comment]
I have a vague memory of this being fixed at some point, maybe around the time most of the tornado got ripped out, or even earlier.
